function [Error,Error_details] = MRI_QC_check(Table,dictionary_MRI)
%% FUNCTION DESCRIPTION
% This function checks for ouliers in the ROI data based on your sample mean 
% Outliers are defined as values more than three scaled mean absolute deviations (MAD) away from the mean
% The error information generated by this function is intended to alert you
% regarding potential implausible values in the ROI data.
%% INPUTS
% Table - string; path to the table containing the data
% dictionary_MRI - string; path to the latest MRI ictionnary
%% OUTPUTS
% Error - cell array of string containing a general error message
% Error_details - cell array of strings containing detailed error information (e.g. the exact PIDs that were found to have ROI outliers)

%% Variable renaming 
MRI_table= Table;
dictionary= dictionary_MRI;
PID = MRI_table.PID;

%% ROI outlier detection
% Get the ROI variables from the data table and remove outliers based on the mean of the current sample
schaefer_ROI_names = dictionary.ItemName(contains(dictionary.ItemName,'schaefer','IgnoreCase', true));
schaefer_ROI = MRI_table{:,contains(MRI_table.Properties.VariableNames,schaefer_ROI_names)};
schaefer_ROI = strrep(schaefer_ROI,'\N','NaN');
schaefer_ROI = cellfun(@str2num, schaefer_ROI);

[ROI_S,tf] = rmoutliers(schaefer_ROI,'mean');
PID_ignored = PID(tf);
%PID_selected = PID(~tf);

% Save general and detailed error information for participants who have outliers in the ROI data
if ~isempty(PID_ignored)
    Error{1,1} = 'Some participants have outliers in their ROI data (more than three scaled mean absolute deviations (MAD) away from the mean). Check the error details for more information.';
end
for i = 1:size(PID_ignored)
  %  disp(['participant ', PID_ignored{i}, ' has been excluded because of outliers in the ROIs (an outlier is a value that is more than three scaled mean absolute deviations (MAD) away from the mean)']);
    Error_details{i,1} = ['participant ', PID_ignored{i}, ' has been excluded because of outliers in the ROIs (an outlier is a value that is more than three scaled mean absolute deviations (MAD) away from the mean)'];
end
end
